services:
  nuevo-1:
    image: prueba:${VERSION_IMAGEN_DOCKER}
    working_dir: /prueba
    environment:
      - PORT=${PUERTO_NODE}
      - PRUEBA=${VAR_PRUEBA}
    ports:
      - ${PUERTO_LOCAL_NODE}:${PUERTO_NODE}
    volumes:
      - '.:/prueba'
    command: ["npm", "run", "start:dev"]

  nuevo-2:
    build:
      context: .
    environment:
      - PRUEBA=Jorge
    ports:
      - 9000:${PUERTO_NODE}
